spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  application:
    name: dev-config
server:
  port: 8202

---
spring:
  profiles: test
  application:
    name: test-config
server:
  port: 8203